# Generated by Django 3.0.4 on 2020-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('resume', models.FileField(upload_to='files/')),
            ],
        ),
    ]
